### ISSUE TITLE
What is kept internally vs what is displayed, causes unexpected results

### ISSUE THREAD

**Issue by parent-tobias** [joshjavier/calculator#2]
To replicate:
I did `3.025 * 9`, which displays rounded to two digits: `27.22`. Then I subtract 27, and get `0.2250`

I suspect the issue is that the full value is being kept (which isn't a bad thing), which can then cause unexpected results (for example, 27.22 * 100 is very different from 27.2249999 * 100). 

Perhaps keeping an internal precision that is "good enough"? For example, while the resulting object contains `27.24999999999`, rounding that to even six decimal places (rather than truncating it) might be a "good enough" solution.

**Comment by joshjavier** [comment]
Thank you for raising this issue!

Indeed, the full value is being stored and operated on. I'm using the `toPrecision` method to truncate the number if it exceeds the buffer limit (10 characters), so it doesn't stretch or spill off of the display.

```js
// if answer exceeds the buffer limit, convert to exponential notation
if (overflow) buffer = Number(value).toPrecision(4).toString();
```

For now, I increased the precision to `5` (not 6 because it causes really big/small numbers to stretch the calculator, like below).

![image](https://user-images.githubusercontent.com/46987872/112755417-2f766a00-9013-11eb-8d86-7511dc947912.png)

It doesn't cover every case, but like you said, it's a "good enough" solution for a beginner project. :smile:
